### ISSUE TITLE
Fine Management

### ISSUE THREAD

**Issue by Dearie-de-cybek** [StarmannRassy/Library-Management-System--Backend-#11]
### User Story
As a member, I want to be notified of fines for overdue books.

### Acceptance Criteria
- [ ] Calculate fines for overdue books
- [ ] Notify users of outstanding fines

### Tasks
- [ ] Implement fine calculation logic
- [ ] Add notification mechanism
- [ ] Write unit tests
