### ISSUE TITLE
User Management and Access Control

### ISSUE THREAD

**Issue by Dearie-de-cybek** [StarmannRassy/Library-Management-System--Backend-#16]
### Admin Story
As an admin, I want to manage user roles and access control.

### Acceptance Criteria
- [ ] Endpoint to manage user roles (admin, librarian, member)
- [ ] Ensure proper access control for different roles

### Tasks
- [ ] Implement role management logic
- [ ] Add access control mechanisms
- [ ] Write unit tests
