### ISSUE TITLE
Admin Registration of Librarians

### ISSUE THREAD

**Issue by Dearie-de-cybek** [StarmannRassy/Library-Management-System--Backend-#18]
### Admin Story
As an admin, I want to be able to register new librarians to manage the library system.

### Acceptance Criteria
- [ ] Admins can register new users with the role of 'librarian'.
- [ ] Only users with the 'admin' role can access this endpoint.
- [ ] The registration process should securely hash the librarian's password.
- [ ] The endpoint should validate the input data (e.g., email, password).
- [ ] A JWT should be returned upon successful registration.
- [ ] Appropriate error messages should be provided for invalid inputs or unauthorized access.

### Tasks
- [ ] Create a new endpoint for admin to register librarians.
- [ ] Implement input validation for the registration form (email, password, role).
- [ ] Ensure that only authenticated admins can access this endpoint.
- [ ] Hash the password before saving the librarian to the database.
- [ ] Write unit tests to cover the registration logic.
- [ ] Document the endpoint in the API documentation.

### Example Request
`POST /api/admin/register-librarian`

#### Request Body
```json
{
  "username": "librarian@example.com",
  "password": "securepassword123",
  "role": "librarian"
}
